FROM sonarqube:9.9.7-community
COPY mule-validation-sonarqube-plugin-1.1.0-SNAPSHOT-mule.jar /opt/sonarqube/extensions/plugins/
COPY rules-4.xml /opt/sonarqube/extensions/plugins/
COPY rules-3.xml /opt/sonarqube/extensions/plugins/
COPY rules-4-custom.xml /opt/sonarqube/extensions/plugins/